# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-24 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstBeat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='isUsed',
            field=models.BooleanField(default=False),
        ),
    ]
